### PR TITLE
Refactoring threading and duplicate method

### PR DESCRIPTION
**Pull request by Jetski5822**
The threading model in the omnisharp file contains overhead in spinning up threads, and there is also a duplicate method that needed to be re-factored in to the main file

### CODE REVIEW

**Comment by jchannon** [comment]
I think the reason for `get_response_from_empty_httppost` was so it didnt send the whole buffer over the network unnecessarily

**Comment by jchannon** [comment]
Apart from that all runs well! Nice work!

**Comment by jchannon** [comment]
Although...

```
 Url: http://localhost:62180/reloadsolution 
 Data: {"line": "22", "column": "71", "buffer": "namespace VQPortal\n{\n    using System;\n    using System.Collections.Generic;\n    using System.Diagnostics;\n    using System.IO;\n    using System.Linq;\n    using Microsoft.AspNet.SignalR;\n    using Microsoft.Owin;\n    using Microsoft.Owin.Cors;\n    using Microsoft.Owin.Extensions;\n    using Microsoft.Owin.FileSystems;\n    using Microsoft.Owin.StaticFiles;\n    using Owin;\n    using Owin.QueryStringToHeader;\n    using Owin.StatelessAuth;\n    using TracingMiddleware;\n    using VQ;\n    using VQ.Classes.Client;\n    using VQ.Configuration._2._0;\n    using VQPortal.Infrastructure.Security;\n    using AssemblyExtensions = VQPortal.Extensions.AssemblyExtensions;\n    using Trace = TracingMiddleware.Trace;\n\n\n    public class Startup\n    {\n        private readonly AppRegistrations appRegistrations;\n        private readonly bool allowSwaggerPOO;\n        \n        public Startup(AppRegistrations appRegistrations)\n        {\n            if (appRegistrations == null)\n            {\n                //TODO UI2 Remove when we have DI done properly!!!\n                //This is required at this point as Proxy::SendMessage is called when ServerConfig is called below which uses ISessionProvider\n                //The correct session provider is VQPortalSessionProvider and registered per request\n                VQSystem.AutoCreateProxy = false;\n                VQSystem.Start();\n\n                Func<IOwinContext, bool> proxyNotRunningFunc = this.ProxyNotRunning;\n                Action<string, string> traceAction = this.Trace;\n\n                appRegistrations = new AppRegistrations(proxyNotRunningFunc, traceAction);\n            }\n\n            this.appRegistrations = appRegistrations;\n\n            var configProvider = this.appRegistrations.ConfigProvider;\n            allowSwaggerPOO = configProvider.GetAppSetting<bool>(\"allowSwagger\");\n        }\n\n        public Startup()\n            : this(null)\n        {\n\n        }\n\n        public void Configuration(IAppBuilder app)\n        {\n            app.Use(TracingMiddleware.Tracing(GetTracingOptions()));\n\n            app.UseCors(CorsOptions.AllowAll);\n\n            app.MapWhen(this.RequestIsStaticFile, builder => builder.UseStaticFiles(GetStaticFileOptions()));\n\n            app.MapWhen(this.appRegistrations.ProxyNotRunningFunc, builder =>\n                {\n                    builder.MapWhen(context => context.Request.Headers[\"Accept\"].Contains(\"application/json\"),\n                        appBuilder => appBuilder.Run(\n                            context =>\n                            {\n                                context.Response.ContentType = \"application/json\";\n                                context.Response.StatusCode = 503;\n                                return context.Response.WriteAsync(\"{\\\"error\\\":\\\"Proxy offline\\\"}\");\n                            }));\n\n                    builder.UseStaticFiles(this.GetStaticFileOptions(proxyDown: true));\n                });\n\n            app.QueryStringToHeader();\n\n            app.RequiresStatelessAuth(new VqTokenValidator(this.appRegistrations.Logger), GetStatelessAuthOptions());\n\n            app.MapSignalR(\"/api/signalr\", new HubConfiguration\n                {\n                    EnableJavaScriptProxies = true,\n                    EnableDetailedErrors = true, // TODO: swap out based on debug\n                });\n\n            app.UseNancy(options => options.Bootstrapper = this.appRegistrations.Bootstrapper);\n\n            app.UseStageMarker(PipelineStage.MapHandler); //StageMarkers are used for static files however nancy has static files in /_Nancy so need to put it down here\n        }\n\n        private bool ProxyNotRunning(IOwinContext arg)\n        {\n            var running = this.TryConnectProxy();\n\n            if (!running)\n            {\n                arg.Request.Path = new PathString(\"/proxydown.html\");\n            }\n\n            return !running;\n        }\n\n        private bool TryConnectProxy()\n        {\n            try\n            {\n                var proxy = new Proxy(); //REMOVE once we have message queues or implement CQS\n                proxy.Disconnect();\n                return true;\n            }\n            catch (ProxyConnectionRetriesExceededException)\n            {\n                return false;\n            }\n        }\n\n        private StatelessAuthOptions GetStatelessAuthOptions()\n        {\n            var ignorePaths = new List<string>(new[]\n                {\n                    \"/api/signalr/hubs\",\n                    \"/api/authenticate/gettoken\",\n                    \"/_Nancy/**\",\n                    \"/favicon.ico\",\n                    \"/api-docs/**\"\n                });\n\n            return new StatelessAuthOptions\n            {\n                IgnorePaths = ignorePaths,\n                WWWAuthenticateChallenge = \"Bearer realm=\\\"VQ Acano Manager API\\\"\"\n            };\n        }\n\n        private TracingMiddlewareOptions GetTracingOptions()\n        {\n            Func<IDictionary<string, object>, bool> internalexceptionfilter = environment =>\n            {\n                if (environment.ContainsKey(\"owin.ResponseStatusCode\"))\n                {\n                    var statuscode = environment[\"owin.ResponseStatusCode\"];\n                    var result = ((int)statuscode == 500 || (int)statuscode == 404 || (int)statuscode == 401 ||\n                                 (int)statuscode == 403);\n                    return result;\n                }\n                return false;\n            };\n            var tracingOptions = new TracingMiddlewareOptions(new Trace(this.appRegistrations.TraceAction),\n                                     TracingMiddlewareOptions.DefaultMessageFormat,\n                                     TracingMiddlewareOptions.DefaultTypeFormat,\n                                     new[] { internalexceptionfilter }).ForType<IDictionary<string, string[]>>(\n                                     headers => string.Join(\",\",\n                                         headers.Select(header => string.Format(\"[{0}:{1}]\", header.Key, string.Join(\",\", header.Value)))));\n\n            return tracingOptions;\n\n        }\n\n        private void Trace(string id, string message)\n        {\n            Debug.WriteLine(\"RequestId : \" + id + \" \" + message);\n            try\n            {\n                var logger = new ClientLogger();\n                logger.Trace(TraceLevel.Verbose, \"VQPortal\", \"OWIN Pipeline\", \"RequestId : \" + id + \" \" + message);\n            }\n            catch (Exception) //Logger goes over the proxy so if proxy is down no logging! FAIL!\n            {\n            }\n        }\n\n        private bool RequestIsStaticFile(IOwinContext context)\n        {\n            if (context.Request.Path == new PathString(\"/index.html\") || context.Request.Path == new PathString(\"/login.html\"))\n            {\n                return true;\n            }\n\n            if (context.Request.Path == new PathString(\"/\"))\n            {\n                context.Request.Path = new PathString(\"/index.html\");\n                return true;\n            }\n\n            PathString remainingPath;\n            if (context.Request.Path.StartsWithSegments(new PathString(\"/static\"), out remainingPath))\n            {\n                context.Request.PathBase = context.Request.PathBase + new PathString(\"/static\");\n                context.Request.Path = remainingPath;\n                return true;\n\n            }\n\n            if (allowSwaggerPOO)\n            {\n                if (context.Request.Path == new PathString(\"/docs/\"))\n                {\n                    context.Request.Path = new PathString(\"/swagger-ui/index.html\");\n                    return true;\n                }\n\n                if (context.Request.Path.StartsWithSegments(new PathString(\"/docs\"), out remainingPath))\n                {\n                    context.Request.PathBase = context.Request.PathBase + new PathString(\"/static\");\n                    context.Request.Path = new PathString(\"/swagger-ui\") + remainingPath;\n                    return true;\n                }\n            }\n\n            return false;\n        }\n\n        private StaticFileOptions GetStaticFileOptions(bool proxyDown = false)\n        {\n            var opt = new StaticFileOptions\n            {\n                FileSystem = new PhysicalFileSystem(Path.Combine(AssemblyExtensions.GetExecutionPath(), \"static\")),\n                RequestPath = PathString.Empty,\n                OnPrepareResponse = context =>\n                {\n                    if (proxyDown)\n                    {\n                        context.OwinContext.Response.StatusCode = 503;//Service Unavailable\n                    }\n                }\n            };\n\n            return opt;\n        }\n\n\n    }\n}\n", "filename": "/Users/jonathan/Projects/vq/VQCore/VQPortal/Startup.cs"}
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/Users/jonathan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 357, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'


```

**Comment by jchannon** [comment]
I think this maybe a timeout issue

**Comment by Jetski5822** [comment]
Not sure, it might be a time out issue, I am going to tweak it slightly so that no params are sent through unless required, and that timeout is only set if passed.

**Comment by jchannon** [comment]
Instead of setting to to 1.0 if not passed in, can you use the sublime setting for timeout please?

**Comment by Jetski5822** [comment]
Okay, changed to take the one passed in, the default being the omnisharp configuration value.... reload project is set at 20.0

Also if both are None, then the urllib3 library will default to an internal value.

**Comment by jchannon** [comment]
Cool. Will take a look over the next few days. Thanks :)

**Comment by jchannon** [comment]
Do you think we should still have the `get_response_from_empty_httppost`

**Comment by jchannon** [comment]
Thanks :+1:

**Pull request merged**
