### PR TITLE
Add code issue tooltips

### PR DESCRIPTION
**Pull request by karlgluck**

### CODE REVIEW

**Comment by karlgluck** [comment]
Hey folks,

This was supposed to go only to our company's local copy of this repo, but I must have angered Github somehow and caused it to PR to you. I'll leave it here in case you find it useful. :)

This code attempts to address issue #132 to pop up a tooltip when the user puts the cursor over an underlined problem.

Other functionality it changes includes:
 * Automatically running the code issue finder on file activate, load, and 500 ms after a change
 * Don't pop the output window when running the code issue finder

**Comment by jchannon** [comment]
Holy crap! This looks awesome. Thank you!

Can't wait to try it out!

**Comment by karlgluck** [comment]
No problem!

If you see anything I need to clean up, let me know. We are attempting to replace MonoDevelop with Sublime 3 for Unity development, so I'm trying to bring over a lot of the functionality we rely on.

**Comment by jchannon** [comment]
Excellent! Hope we can enhance this plugin to be much better

**Comment by jchannon** [comment]
I've just tried this locally and its great!

How hard do you think it would be to show the error popup when the cursor hovers over the area that has issues rather than needing a mouse click?

**Comment by karlgluck** [comment]
As far as I can tell, there is no API for mouse input in Sublime Text 3. Am I missing something?

**Comment by jchannon** [comment]
I think there is as the README on this seems to suggest it https://github.com/jbrooksuk/Intellitip

However I don't really know the Sublime API in that area very well

**Comment by karlgluck** [comment]
I used that code as a reference to write this. The text cursor triggers the popover, not the mouse. :( I've looked everywhere but ST doesn't seem to reveal your mouse location.

**Comment by jchannon** [comment]
Ah ok

**Comment by jchannon** [comment]
Could you add a plugin setting to show the error window?

**Comment by jchannon** [comment]
Thanks @karlgluck this is awesome stuff! All merged! Keep those PRs coming :wink:

**Comment by jchannon** [comment]
@karlgluck do you fancy looking at the type lookup stuff as well?

I'm assuming the tooltips appear when the caret is in the region that is drawn by the errors or is it something to do with the oops_map which is put into the view settings? Just trying to understand how this works :smile:

**Comment by sayedihashimi** [comment]
Anyone have a screenshot?

**Comment by sayedihashimi** [comment]
Found screenshot https://pbs.twimg.com/media/CBmjCLYVIAAJvW9.png:large

**Comment by jchannon** [comment]
Yup - https://twitter.com/omnisharp/status/583676885986447360

**Pull request merged**
