### PR TITLE
Fixes #161 - Scoping call to OnSave and OnModify and refector data

### LINKED ISSUE #161: "omnisharp_onsave_showerrorwindows" shows errors every time an error is detected instead of on save.
1.9.1 ... With "omnisharp_onsave_showerrorwindows" set to true, the error window pops up every time an error is detected while editing, instead of on save only.

### PR DESCRIPTION
**Pull request by Jetski5822**
Scoping the calls for IsSave and IsModify, and also removing the data attribute attached to self.

### CODE REVIEW

**Comment by jchannon** [comment]
Where is isModify used?

**Comment by Jetski5822** [comment]
it's not, more there for sanity. Want me to remove it?

**Comment by jchannon** [comment]
I think what I plan to do is remove the on activated and on modified so it
handles only the on save method however I'd like the threading thing
identified and fixed first then remove those two methods

**Comment by Jetski5822** [comment]
Threading is not the issue. The problem is that on_modified and on_save call the same method, which in this case would always call this...

        if bool(helpers.get_settings(view, 'omnisharp_onsave_codecheck')):
            omnisharp.get_response(view, '/codecheck', self._handle_codeerrors)

so if that is set to true in the settings, then on_modifided will run it too

**Comment by Jetski5822** [comment]
Or have I miss understood the issue?

**Comment by jchannon** [comment]
There's a addtoproject listener too so I'm thinking when a files is saved.
Get response is called at the same time and it's somehow messing up. For
example oth get called and when there are syntax errors they're not getting
reported for some reason

**Comment by Jetski5822** [comment]
You have a other issues with addtoproject, i.e. it seems to fire off to the server even if it has not filename, so the server ends up throwing a 500 error.

**Comment by jchannon** [comment]
Maybe but try using a file in your project already. Set int i = "Blah"; and
save the file and watch the response. In some cases it says there is no
errors so it looks like addtoproject and code check are clashing somehow

**Comment by Jetski5822** [comment]
Ah I miss read the issue. Okay so, hmm... addtoproject should not even be getting called...

**Comment by jchannon** [comment]
It should if the file is on disk

**Comment by Jetski5822** [comment]
but, why is it getting called when the file is already in your project?

**Comment by jchannon** [comment]
Good point. Not sure how you know if it is though. @nosami ?

**Comment by nosami** [comment]
why don't you both come in Jabbr? :)

**Comment by Jetski5822** [comment]
@jchannon Okay, after getting a project file that was working I cannot seem to repro this issue. Can you try with the changes I made in this file?

**Comment by jchannon** [comment]
I'm pretty sure your change will fix it but it doesn't solve the issue of
future potential issues when we might have 2 requests called at the same
time :(

**Comment by robbert229** [comment]
Unless I am mistaken this PR isn't really relevant anymore, atleast it is not up to date with the current version of `omnisharp-sublime` therefor closing.

**Pull request closed without merging**
