### PR TITLE
Build console improvements

### PR DESCRIPTION
**Pull request by maliayas**
This PR is a showcase for the unfinished work in `build-console-improvements` branch. Not ready to merge, yet.

### CODE REVIEW

**Comment by maliayas** [comment]
I've implemented highlighting unit test output. Screenshot:

ekran goruntusu 2015 04 02 03_15_23

In order to use it;

* Update your personal `.sublime-build` file similar to <https://github.com/maliayas/omnisharp-sublime/blob/build-console-improvements/OmniSharpSublime.sublime-build>. Important keys are `syntax` and `file_regex`.
* Restart Sublime Text.
* Run unit tests!

Notes:

* I suggest adding a default and real `.sublime-build` file to the project. If there are common tasks that most people would like to have, this would make their life easier. Currently I've added a `.sublime-build` file but that's only for test purposes.

* I tried to highlight your unit test output sample but probably it is too basic. So when you notice new stuff that should be highlighted as well, please post them here.

* Highlighting build output will be available tomorrow. Currently only unit test output is highlighted.

* If output contains paths, you should be able to open them by doubleclicking on it. When this doesn't work, post it here so I'll try to fix.

* Color feedback is welcome.

/cc @jchannon 
/cc @nathanaeljones

**Comment by sayedihashimi** [comment]
This is looking really good!

**Comment by jchannon** [comment]
This looks amazing!!

Colour wise, just a personal pref but I think I'd change the purple on the Total but I'm not that bothred :smile: because this is great.

We don't ship a `sublime-build` file we do builds via code and as you've seen from the docs it shows how you can make your own build file.

Here is where we execute the build https://github.com/OmniSharp/omnisharp-sublime/blob/master/commands/build_project.py#L34 and I have commented code in there so I can set the theme and syntax colours so would you mind changing that?  The `file_regex` may need updating to be better but seems to work at the moment.

The unit test code is here https://github.com/OmniSharp/omnisharp-sublime/blob/master/commands/run_unit_tests.py#L28, this will also need the `file_regex` adding and code for setting the theme.

I'm happy to do the above if you prefer but this is really great, thanks again!

@nathaneljones thanks for telling @maliayas about this :+1:

**Comment by maliayas** [comment]
* Color scheme is now used from python.
* Dummy build file removed
* "Total: XX" color is changed
* "Save all" before the build is now smarter. It doesn't try saving files that's not on disk yet. If you don't like this approach, we can revert it.

Above commits were mainly about refactoring. Colors and styling will be improved tomorrow. For the curious, here is the uncommited status from my dev env:

ekran goruntusu 2015 04 04 03_03_09

**Comment by maliayas** [comment]
BTW, I'm not able to actually run a real xunit test. Those stuff is not installed on my computer. Could you please report me if latest changes break any functionality?

**Comment by jchannon** [comment]
I've just pulled this and ran it on some tests and it looks amazing!

I can't see any broken functionality.  When there is a bild error I can press F4 and it takes me to the line where the error is, do you think its possible to do this for failed tests? I'm not sure it is as the failed test output doesn't give line numbers and column numbers but thought I'd ask.

This is really great work, thanks a million!

**Comment by maliayas** [comment]
I've finished my work. Based on the feedback, we can change stuff.

Unit test highlighting:

ekran goruntusu 2015 04 05 16_09_08

Build output highlighting:

ekran goruntusu 2015 04 05 16_08_39

**Comment by maliayas** [comment]
> do you think its possible to do this for failed tests? I'm not sure it is as the failed test output doesn't give line numbers and column numbers but thought I'd ask.

Unfortunately not. It requires a suit what will match classes/methods to files. But if you are able to output paths by configuring your test library, it becomes possible easily.

**Comment by jchannon** [comment]
This is amazing!! Huge appreciation for this.

**Comment by maliayas** [comment]
You're welcome. Glad you like it!

**Comment by jchannon** [comment]
Will make my life a lot easier!!

**Pull request merged**
