### PR TITLE
Fix OmniSharpServer.exe crash on startup.

### PR DESCRIPTION
**Pull request by chryan**
The solution and config file paths need to be quoted for paths that have spaces in them.

### CODE REVIEW

**Comment by jchannon** [comment]
Is this a result of the 1.8.0 release out of interest?

**Comment by nosami** [comment]
Looks like a fix for spaces in the solution path.

**Comment by chryan** [comment]
Yes this is actually a result of the very recent 1.8.0 release.
I think this is only an issue on Windows systems.

**Comment by jchannon** [comment]
Thanks for the PR. I've put out a new release. I'm not really testing on
Windows so if you come across any issues feel free to do some more PRs =)

**Comment by andzdroid** [comment]
The -s change has broken omnisharp on my mac, it's using too many quotes, eg. `-s ""/Users/andz/project.sln""`

The change for -config is working correctly.

**Comment by andzdroid** [comment]
Actually never mind, the double quoting isn't the problem, doesn't actually break anything apparently.

I'll submit a separate issue for my problem.

**Comment by jchannon** [comment]
Feel free to do a PR for the double quoting.

See #135 to see if that helps.

Sublime and Omnisharp seems to be a bit flaky at the mo so I'd like to
track down the issues

**Pull request merged**
