### PR TITLE
Multiple OmniSharp Versions Support

### PR DESCRIPTION
**Pull request by robbert229**
I added in a Roslyn binary as well as updating the old OmniSharp server. It is possible to add and remove versions of OmniSharp via the configuration files. Swapping the active server can be done without even closing sublime text or any of its' tabs.

Also I am planning on rebasing after I have everything sorted out.

### CODE REVIEW

**Comment by karlgrz** [comment]
@robbert229 I just checked out your branch, I'll use it during the workday here and give feedback later on. Seems to be working well thus far.

**Comment by karlgrz** [comment]
@robbert229 seems to be working well for me.

**Comment by robbert229** [comment]
Did you swap between roslyn and legacy?

**Comment by karlgrz** [comment]
@robbert229 yes, seemed to work ok.

**Pull request merged**
