### PR TITLE
Added setting 'omnisharp_show_override_completion'

### PR DESCRIPTION
**Pull request by invicticide**
Added a setting to control whether the override code completion popup appears after typing "override". Addresses issue #193.

### CODE REVIEW

**Comment by aMoniker** [comment]
Nice. Are there any other triggers that cause the same style of popup?

**Comment by invicticide** [comment]
None I've stumbled across. Certainly nothing anywhere *near* as annoying as that override popup. ;)

**Comment by jchannon** [comment]
For some reason Github says it can't merge this. Any ideas?

**Comment by invicticide** [comment]
@jchannon I don't know, I'm not familiar with *accepting* pull requests. The two changes are super trivial though.

**Comment by leye0** [comment]
Has this be merged?

**Comment by aMoniker** [comment]
It doesn't look like it. @invicticide can you pull a fresh copy of master and rebase your changes in this branch so the PR can be accepted?

**Comment by invicticide** [comment]
Resubmitted. Maybe this one will work?

**Comment by robbert229** [comment]
Looks good to me!

**Pull request merged**
